// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FlashcardFromIDResp {
    id: number;
    folderId: number;
    term: string;
    definition: string;
}
