// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GroupGetResp {
    id: number;
    name: string;
    rootFolder: number;
    uuid: string;
}
