// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberDetails } from "./MemberDetails";
import type { MemberType } from "./MemberType";
import type { UserDetails } from "./UserDetails";

export interface GroupInfoGetResp {
    uuid: string;
    name: string;
    rootFolder: number | null;
    isPublic: boolean;
    memberType: MemberType | null;
    isRequestPending: boolean;
    members: Array<MemberDetails>;
    requests: Array<UserDetails> | null;
}
