// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mode } from "./Mode";

export interface NextFlashcardGetResp {
    mode: Mode;
    flashcardIds: string;
}
