// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberType } from "./MemberType";

export interface UserGroup {
    id: number;
    name: string;
    description: string;
    isPublic: boolean;
    role: MemberType;
}
