# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: /usr/bin/env make lint
        language: script
