version: "3.9"

services:
  postgres_auth:
    container_name: postgres_auth
    image: "postgres:latest"
    env_file:
      - ./database.dev.env
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin_auth
    image: dpage/pgadmin4
    env_file:
      - ./database.dev.env
    ports:
      - 5050:80
    networks:
      - backend

  keycloak:
    container_name: keycloak_auth
    image: jboss/keycloak
    depends_on:
      - "postgres_auth"
    env_file:
      - ./keycloak.dev.env
    ports:
      - 8180:8080
      - 8787:8787 # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
