# Source: https://herewecode.io/blog/create-a-postgresql-database-using-docker-compose/
version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBNAME}

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
